# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [46]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [47]:
A = np.arange(1, 16).reshape(3,5)

In [54]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)



2
(3, 5)
15
int64


In [52]:
A = A.reshape(3,5)

In [53]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [43]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [44]:
np.subtract(B, C)

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [19]:
print(np.multiply(B,C))

print(B * C)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [ ]:
B @ C

array([[12., 12., 12.],
       [30., 30., 30.],
       [48., 48., 48.]])

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [21]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
# variables
B = np.arange(1, 10).reshape(3, 3)
E = np.exp(8)
min_val = np.min(B)
mini_row = np.min(B, axis=1)
mini_col = np.min(B, axis=0)
mini_index = np.argmin(B, axis=1)
mini_index_row = np.argmin(B, axis=0)
sum = np.sum(B, axis=1)
col = np.mean(B, axis=0)
median_col = np.median(B, axis=1)

#output
print(B)
print()
print(E)
print()
print (min_val)
print()
print(mini_row)
print()
print(mini_col)
print()
print(mini_index)
print()
print(mini_index)
print()
print(mini_index_row)
print()
print(sum)
print()
print(col)
print()
print(median_col)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

2980.9579870417283

1

[1 4 7]

[1 2 3]

[0 0 0]

[0 0 0]

[0 0 0]

[ 6 15 24]

[4. 5. 6.]

[2. 5. 8.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [55]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [56]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [ ]:
# 1. You print out whatever exist inside A.
# 2. You get whatever exists in index 1 in A

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [57]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [35]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [58]:
A = np.array ([[4, 8, 16], [28, 46, 128]])

for element in np.nditer(A):
    print(element)

4
8
16
28
46
128


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [61]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
# 1. Output is the original array valued from 0 - 29
# 2. Skapar två block som är 3 x 5


# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [62]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [63]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [64]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [65]:
def add_mult_matrices(A, B, operation):
    # Validate that the inputs are numpy arrays
    if not isinstance(A, np.ndarray) or not isinstance(B, np.ndarray):
        raise ValueError("Both inputs must be of type numpy.ndarray")

    # Validate that the operation is either 'add' or 'multiply'
    if operation not in ['add', 'multiply']:
        raise ValueError("The operation must be either 'add' or 'multiply'")

    # Matrix Addition
    if operation == 'add':
        # Validate that the matrices have the same shape for addition
        if A.shape != B.shape:
            raise ValueError("Matrices must have the same shape for addition")
        return A + B

    # Matrix Multiplication
    elif operation == 'multiply':
        # Validate that the number of columns of A is equal to the number of rows of B
        if A.shape[1] != B.shape[0]:
            raise ValueError("Number of columns of A must equal the number of rows of B for multiplication")
        return np.dot(A, B)

# Example usage:
A = np.array([[5, 3], [7, 9]])
B = np.array([[2, 8], [6, 3]])

# Addition example
result_add = add_mult_matrices(A, B, 'add')
print("Matrix Addition Result:\n", result_add)

# Multiplication example
result_multiply = add_mult_matrices(A, B, 'multiply')
print("Matrix Multiplication Result:\n", result_multiply)

Matrix Addition Result:
 [[ 7 11]
 [13 12]]
Matrix Multiplication Result:
 [[28 49]
 [68 83]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. 

In [ ]:
import numpy as np

x = np.array([4,3])


In [2]:
# 10.1.1 a)

dimension = x.ndim
print(f' Dimension of x: {dimension}')

 Dimension of x: 1


In [ ]:
# 10.1.1 b) Calculate 5x

x_times_5 = 5 * x 
print(f' Element 1: 5 * {x[0]} = {5 * [0]}')
print(f' Element 2: 5 * {x[1]} = {5 * [1]} ')
print(f'Result: {x_times_5}')

# Troubleshoot:
# Why do I get 5 * 4 = [0,0,0,0,0] and 5 * 3 = [0,0,0,0,0] instead of 20 and 15?
# Added a x before [0] and [1] fixed the problem. 

 Element 1: 5 * 4 = [0, 0, 0, 0, 0]
 Element 2: 5 * 3 = [1, 1, 1, 1, 1] 
Result: [20 15]


In [ ]:
# 10.1.1 c) Calculate 3x
x_times_3 = 3 * x
print(f' Element 1: 3 * {x[0]} = { 3 * x[0]}')
print(f' Element 1: 3 * {x[1]} = { 3 * x[1]}')
print(f' Result: {x_times_3}')


 Element 1: 3 * 4 = 12
 Element 1: 3 * 3 = 9
 Result: [12  9]


In [ ]:
# 10.1.1 d) calculate 5x + 3x

x5 = 5 * x # Multiply
print(f' {x5}')
x3 = 3 * x
print(f' {x3}')
print(f' 5x = {x5}, 3x = {x3}')

sumx5x3 = x5 + x3 # addition
print(f' {sumx5x3}')
print (f' {x5[0]} + {x3[0]} = {sumx5x3[0]}')
print (f' {x5[1]} + {x3[1]} = {sumx5x3[1]}')


 [20 15]
 [12  9]
 5x = [20 15], 3x = [12  9]
 [32 24]
 20 + 12 = 32
 15 + 9 = 24
 


In [ ]:
# 10.1.1 e) Calculate 8x

x8 = 8 * x
print(f' 8 * 4 = {x8[0]}')
print(f' 8 * 3 = {x8[1]}')
print(f' Result: {x8}')

 8 * 4 = 32
 8 * 3 = 24
 Result: [32 24]


In [51]:
# 10.1.1 f) Calculate 4x - x

x4 = 4 * x # Multiply
print(f' 4x = {x4}')

four_minus_x = x4 - x # Substraction 
print(f' {x4[0]} - {x[0]} = {four_minus_x[0]}')
print(f' {x4[1]} - {x[1]} = {four_minus_x[1]}')


 4x = [16 12]
 16 - 4 = 12
 12 - 3 = 9


In [ ]:
# 10.1.1 f)
x = np.array([4,3])

x_transpose = x.reshape(-1, 1)

print(f' Original {x} Shape {x.shape}')
print(f' Transpose {x_transpose}')

 Original [4 3] Shape (2,)
 Transpose [[4]
 [3]]


In [60]:
# 10.1.1 g)

x_transpose.shape

(2, 1)

In [64]:
# 10.1.1 h) is x + xt defined?

x_transpose = x.reshape (-1, 1)

is_defined = x.shape == x_transpose.shape

print(f"Original vector x: {x} (Shape: {x.shape})")
print(f"Transpose of x:{x_transpose} (Shape: {x_transpose.shape})")
print(f"Is x + xᵀ defined? {is_defined}")


Original vector x: [4 3] (Shape: (2,))
Transpose of x:[[4]
 [3]] (Shape: (2, 1))
Is x + xᵀ defined? False


In [71]:
x = np.array([4, 3])

#Squares
squares = x ** 2
print(f' {squares}')

#Sum
sum_of_squares = np.sum(squares)
print(f' {sum_of_squares}')

a = np.sqrt(sum_of_squares)
print(f' {a}')

a2 = np.linalg.norm(x)
print(f' {a2}')

 [16  9]
 25
 5.0
 5.0


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [72]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [73]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [74]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
